### ISSUE TITLE
Separate configuration for polling vs event tracking settings

### ISSUE THREAD

**Issue by strawgate** [legrego/homeassistant-elasticsearch#282]
I think it might be more intuitive for us to separate configurations for polling from configurations for events.

Right now we have:
* All entities
* Entities with State Changes
* Entities with Any Changes

Part of me is wondering if we should do something like:

Polling
- [ ] Publish all entities to Elasticsearch every publish interval

When an entity updates
- [ ] Publish the entity
- [ ] Publish the entity only when its state value changes

**Comment by legrego** [comment]
I like this proposal, I'd be happy to see us take this approach.
https://github.com/legrego/homeassistant-elasticsearch/pull/272 is already massive, so let's wait for that to merge before taking this on.

**Comment by strawgate** [comment]
Most of the issues I created yesterday are 2.0 issues, I'm wrapping up that config pr hopefully today
