### ISSUE TITLE
Support Elasticsearch 7.x

### ISSUE THREAD

**Issue by legrego** [legrego/homeassistant-elasticsearch#57]
## TODO
- [x] Remove document type
- [ ] Branch for 6.x version
- [x] Fix index template (https://github.com/legrego/homeassistant-elasticsearch/issues/60)
